### ISSUE TITLE
Question about 'run_spiral_DLPFC.ipynb'

### ISSUE THREAD

**Issue by xkmaxidian** [guott15/SPIRAL#4]
Hi, dear authors,

Thank you for sharing such interesting work! I am currently attempting to reproduce the results of DLPFC integration. However, the model training process shows 0% progress even after an hour of executing `SPII.train()` on the RTX4090 device.
Could you please provide the trained model? This would be immensely helpful for my research.
Thank you in advance for your assistance.

**Comment by guott15** [comment]
Hi,
&nbsp; &nbsp;Thanks for your question. I'm sorry to say that the SPIRAL is slow becuase of the GraphSAGE training procedure， to alleviate this problem, I recommond you two methods:
1. reduce the number of used genes by choosing 500 HVG in each sample and get the union of 12 samples;
2. you can use the pytorch version of SPIRAL, whose address have been supplied.


best wishes!






guott15
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guott15/SPIRAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 下午4:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[guott15/SPIRAL] Question about 'run_spiral_DLPFC.ipynb' (Issue #4)





 
Hi, dear authors,
 
Thank you for sharing such interesting work! I am currently attempting to reproduce the results of DLPFC integration. However, the model training process shows 0% progress even after an hour of executing SPII.train() on the RTX4090 device.
 Could you please provide the trained model? This would be immensely helpful for my research.
 Thank you in advance for your assistance.
